### PR TITLE
RoundedSimple - Rounded with variable precision

### PR DESCRIPTION
**Pull request by michalkonecny**
Hi,

In this branch, I have added Numeric.RoundedSimple, which provides a version of the type Rounded which is not parametrised by the precision and rounding mode.  Instead, one can set the precision and rounding mode like in MPFR.  This alternative interface is useful in applications where precision is frequently adjusted.

In the process of cloning Numeric.Rounded into Numeric.RoundedSimple, I have separated all the FFI imports into module Numeric.MPFR.Functions so that it can be shared with Numeric.Rounded.  Nevertheless, as I have not touched Numeric.Rounded, this is currently still duplicated.  To remove the duplication, one can import Numeric.MPFR.Functions in Numeric.Rounded instead of importing the C functions one by one.

Lastly, I have added 3 lines to Numeric.MPFR.Types.hsc so that it compiles with ghc 7.10 as well as newer ghc:

```
#if __GLASGOW_HASKELL__ < 800
#let alignment t = "%lu", (unsigned long)offsetof(struct {char x__; t (y__); }, y__)
#endif
```

I added the same 3 lines also to `Numeric/GMP/Types.hsc` in my copy of hgmp.  I recommend to make this change upsteam in hgmp.  (I am currently on ghc-7.10 due to a serious bug in 8.0.2).

### CODE REVIEW

**Comment by claudeha** [comment]
Sorry for delay.  Thanks, I added the alignment macro to hgmp-0.1.1 now released on Hackage, and I'll add it to my rounded too.  I'm not sure I'll merge this as-is, but the idea seems sensible.  I'll try to figure out how to avoid the code duplication.

**Comment by claudeha** [comment]
I tried a slightly different approach, with some simpler naming too: https://code.mathr.co.uk/rounded/blob/refs/heads/claude5:/src/Numeric/Rounded/Simple.hs I'm unsure how to correctly implement the RealFrac-alike functions, so I left them TODO for now.  Thoughts?

**Comment by michalkonecny** [comment]
Hi Claude, thank you for your response and suggestion of a different approach.  I previously considered a similar approach to yours but was concerned that it could lead to a significant loss of performance.  Franz Brausse has implemented a benchmark ([fbrausse/rounded@8fa5206](https://github.com/fbrausse/rounded/commit/8fa52064c604a1c3fb0754cb0fdcfddf2c18c98f)) comparing both proposed versions of Rounded.Simple.  For my purposes, the differences in performance between your code and my code are not significant.  I would be happy to adapt my library to use the version you proposed.

Franz is currently using my fork of rounded in [Kirk](https://github.com/fbrausse/kirk) to power a Haskell interface to [iRRAM](http://irram.uni-trier.de/).  He plans to move to the official fork of rounded.  He is likely to need some API additions to make it work.  I am not yet sure to what degree the choice of approach for Rounded.Simple will impact Franz's work.  I hope it is possible to expose what he needs from either solution.

**Comment by claudeha** [comment]
Regarding the benchmarks, I imagine with most use of libmpfr (using larger precisions than native double) the C library runtime will dominate any FFI interface.

I wouldn't call my fork any more official than yours. edk's I guess is the official one but it seems abandoned...

I would rather rename the two exported helper functions to something less "internal"-looking.  Probably `out_''` could be named similar to `peek` and `in_'` like `with`.

I should have time to merge the recent changes this week.

**Comment by fbrausse** [comment]
Hello Claude and Michal, thank you for both for the work on Rounded/Simple! I agree that the FFI calls won't dominate running time for non-pathological cases (like iterating `x_{n+1}=-x_n`). Regarding `out_''` and `in_'`, what I basically need in Kirk is a way to treat an `mpfr_t` instance generated in memory by code unrelated to the Rounded library as an instance of the simple `Rounded` type as well as the reverse: map such an instance to a raw `mpfr_t` which Haskell-unrelated code can call functions from the mpfr library on. The latter reason is why using the alternative [hmpfr](https://github.com/michalkonecny/hmpfr) library is difficult: it uses non-mpfr functions to manage memory for the limbs, s.t. reallocating mpfr-calls fail. However, Rounded does not have this restriction.

Claude, using your approach, are there any arguments against exposing functions `peek` and `with` (the names you suggested obviously are better than my ad-hoc ones)?

**Comment by claudeha** [comment]
https://github.com/claudeha/rounded/commit/9cc8e0476045df90c0259f71eadbfb4b18de6013 adds the FFI helpers for the Simple variant, sorry for the delay, I was busier than I thought I would be...

**Comment by michalkonecny** [comment]
Many thanks!  I have just adapted aern2-mp to using Rounded.Simple.  Except for one small issue it works well.  The small issue is that the "precision" function is not exported.  I would be most grateful if you could please export "precision" in Numeric.Rounded.Simple.  Thank you for all your help!

I and Franz (and probably others) would greatly benefit if an up-to-date rounded was on Hackage.  Have you heard from Ed regarding his plans for rounded?  If there is something that needs doing before rounded can go to Hackage (such as adding tests), I could possibly help.

**Comment by michalkonecny** [comment]
Many thanks for adding the export.

**Pull request closed without merging**
